services:
  nginx:
    image: nginx
    build: 
      context: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - medpseg
    volumes:
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - medpseg

  medpseg:
    image: medpseg
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - medpseg_db:/db
    ports:
      - 8502:8502
    networks:
      - medpseg
    environment:
      - TINYDB_PATH=${TINYDB_PATH}
      - MEDPSEG_CMD=${MEDPSEG_CMD}
  
volumes:
  medpseg_db:

networks:
  medpseg:
    driver: bridge