[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "medpseg"
version = "5.0.0"
description = "Modified EfficientDet for Polymorphic Pulmonary Segmentation (MEDPSeg)"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    {name = "Diedre Carmo", email = "diedre@unicamp.br"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "rich",
    "pillow",
    "scipy",
    "tqdm",
    "torch",
    "pandas",
    "torchvision",
    "pytorch-lightning",
    "efficientnet-pytorch",
    "connected-components-3d",
    "psutil",
    "gputil",
    "opencv-python",
    "SimpleITK",
    "pydicom",
    "matplotlib",
    "timm",
    "torchinfo",
    "monai",
    "imageio",
    "nibabel",
    "wget",
    "json2table",
    "streamlit",
    "streamlit-scrollable-textbox",
    "streamlit-aggrid",
    "tinydb",
    "python-dotenv",
]

[project.scripts]
medpseg = "medpseg.run:main"
medpseg_cpu = "medpseg.run:main_cpu"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
namespaces = false

[tool.setuptools.package-data]
medpseg = [
    "assets/icon.png",
    "assets/icon_original.png",
    "assets/coronacases_100_003.png",
    "assets/respiratory.gif",
    "assets/diseased.gif",
    "poly_medseg_25d_fix.ckpt",
    "poly_lung.ckpt",
    "lober.ckpt",
]
